version: '3'

services:
  fincheck-api-pg:
    container_name: fincheck-api-pg
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fincheckapi
